# Generated by Django 5.2.6 on 2026-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text="FontAwesome class (e.g., 'fab fa-python')", max_length=50),
        ),
    ]
